Data Inspection

In [41]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [42]:
df = pd.read_csv(r"C:\Users\muhmm\project_4.1\Data\samplesuperstore.csv")

In [43]:
df.shape

(10194, 21)

In [44]:
df.dtypes

Row ID              int64
Order ID              str
Order Date            str
Ship Date             str
Ship Mode             str
Customer ID           str
Customer Name         str
Segment               str
Country/Region        str
City                  str
State/Province        str
Postal Code           str
Region                str
Product ID            str
Category              str
Sub-Category          str
Product Name          str
Sales             float64
Quantity            int64
Discount          float64
Profit            float64
dtype: object

In [45]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [46]:
df[["Sales", "Profit", "Quantity","Discount" ]].describe()

              Sales        Profit      Quantity      Discount
count  10194.000000  10194.000000  10194.000000  10194.000000
mean     228.225854     28.673417      3.791838      0.155385
std      619.906839    232.465115      2.228317      0.206249
min        0.444000  -6599.978000      1.000000      0.000000
25%       17.220000      1.760800      2.000000      0.000000
50%       53.910000      8.690000      3.000000      0.200000
75%      209.500000     29.297925      5.000000      0.200000
max    22638.480000   8399.976000     14.000000      0.800000

In [47]:
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,1/3/2023,1/7/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717

Data Cleaning

In [48]:
print(df.duplicated().sum())
dupes = df[df.duplicated(subset=["Order ID"], keep=False)]
print(dupes.shape)
dupes.head()

0
(7601, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
5,6,US-2023-167199,1/6/2023,1/10/2023,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.820,9,0.0,746.4078
6,7,US-2023-167199,1/6/2023,1/10/2023,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-AR-10001662,Office Supplies,Art,Rogers Handheld Barrel Pencil Sharpener,5.480,2,0.0,1.4796

In [49]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])
df['shipping Date'] = (df['Ship Date'] - df['Order Date']).dt.days
print(df['shipping Date'].describe())

count    10194.000000
mean         3.961350
std          1.742829
min          0.000000
25%          3.000000
50%          4.000000
75%          5.000000
max         11.000000
Name: shipping Date, dtype: float64

In [50]:
print(df.groupby('Region')[ 'shipping Date'].mean())

Region
Central    4.053533
East       3.913262
South      3.959259
West       3.940363
Name: shipping Date, dtype: float64

In [51]:
df['Profit Margin'] = df['Profit'] / df['Sales']*100.
df['Profit Margin'] = df['Profit Margin'].round(2)
print(df.groupby('Sub-Category')['Profit Margin'].mean().sort_values().round(2))

Sub-Category
Binders       -19.46
Appliances    -14.90
Tables        -14.02
Bookcases     -13.51
Machines       -6.89
Chairs          4.71
Storage         9.08
Supplies       11.44
Phones         12.25
Furnishings    13.98
Accessories    21.82
Art            25.22
Fasteners      30.63
Copiers        32.04
Envelopes      42.35
Labels         42.46
Paper          42.50
Name: Profit Margin, dtype: float64

In [52]:
df['Order Year'] = df['Order Date'].dt.year

In [53]:
df.rename(columns={'Sub-Category': 'sub_category', 'Ship Mode': 'ship_mode', 'Customer Name': 'customer_name',
                    'Order Year': 'order_year', 'shipping Date': 'shipping_date', 'Profit Margin': 'profit_margin', 
                    'Sales': 'sales', 'Profit': 'profit', 'Order Date': 'order_date', 'Ship Date': 'ship_date',
                    'Region': 'region', 'Customer ID': 'customer_id', 'Order ID': 'order_id', 'Category': 'category',
                    'Customer Name': 'customer_name', 'Row ID': 'row_id', 'Segment': 'segment', 'Quantity': 'quantity',
                    'Product Name': 'product_name','Discount': 'discount', 'Product ID': 'product_id',
                    'Country/Region': 'country_region','City': 'city', 'Postal Code': 'postal_code'}, inplace=True)

In [54]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country_region', 'city',
       'State/Province', 'postal_code', 'region', 'product_id', 'category',
       'sub_category', 'product_name', 'sales', 'quantity', 'discount',
       'profit', 'shipping_date', 'profit_margin', 'order_year'],
      dtype='str')

In [55]:
df.to_csv(r"C:\Users\muhmm\project_4.1\Data\cleaned_superstore.csv", index=False)